import {defineType, defineField, defineArrayMember} from 'sanity'
import {DocumentsIcon} from '@sanity/icons'

export const listingPage = defineType({
  name: 'listingPage',
  title: 'Listing Page',
  type: 'document',
  icon: DocumentsIcon,
  preview: {
    select: {title: 'title', subtitle: 'route'},
    prepare({title, subtitle}) {
      const routeLabel = subtitle
        ? `/${subtitle} — ${subtitle.charAt(0).toUpperCase() + subtitle.slice(1)}`
        : 'Unconfigured'
      return {title: title || routeLabel, subtitle: routeLabel}
    },
  },
  fields: [
    defineField({
      name: 'route',
      title: 'Route',
      type: 'string',
      description:
        'Which listing page this document configures. Set automatically — do not change.',
      options: {
        list: [
          {title: 'Articles', value: 'articles'},
          {title: 'Authors', value: 'authors'},
          {title: 'Events', value: 'events'},
          {title: 'Projects', value: 'projects'},
          {title: 'Sponsors', value: 'sponsors'},
        ],
        layout: 'radio',
      },
      readOnly: true,
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'title',
      title: 'Page Title',
      type: 'string',
      description: 'Overrides the default H1 heading. Leave blank to use the default.',
      validation: (Rule) => Rule.max(150),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      description: 'Optional intro paragraph displayed below the heading.',
      rows: 3,
      validation: (Rule) => Rule.max(500),
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
    }),
    defineField({
      name: 'headerBlocks',
      title: 'Header Blocks',
      description: 'Optional content blocks rendered ABOVE the listing.',
      type: 'array',
      of: [
        defineArrayMember({type: 'heroBanner'}),
        defineArrayMember({type: 'featureGrid'}),
        defineArrayMember({type: 'sponsorCards'}),
        defineArrayMember({type: 'richText'}),
        defineArrayMember({type: 'ctaBanner'}),
        defineArrayMember({type: 'faqSection'}),
        defineArrayMember({type: 'contactForm'}),
        defineArrayMember({type: 'logoCloud'}),
        defineArrayMember({type: 'statsRow'}),
        defineArrayMember({type: 'sponsorSteps'}),
        defineArrayMember({type: 'textWithImage'}),
        defineArrayMember({type: 'testimonials'}),
        defineArrayMember({type: 'eventList'}),
        defineArrayMember({type: 'projectCards'}),
        defineArrayMember({type: 'teamGrid'}),
        defineArrayMember({type: 'imageGallery'}),
        defineArrayMember({type: 'articleList'}),
        defineArrayMember({type: 'comparisonTable'}),
        defineArrayMember({type: 'timeline'}),
        defineArrayMember({type: 'pullquote'}),
        defineArrayMember({type: 'divider'}),
        defineArrayMember({type: 'announcementBar'}),
        defineArrayMember({type: 'sponsorshipTiers'}),
        defineArrayMember({type: 'videoEmbed'}),
        defineArrayMember({type: 'pricingTable'}),
        defineArrayMember({type: 'serviceCards'}),
        defineArrayMember({type: 'productShowcase'}),
        defineArrayMember({type: 'linkCards'}),
        defineArrayMember({type: 'newsletter'}),
        defineArrayMember({type: 'accordion'}),
        defineArrayMember({type: 'tabsBlock'}),
        defineArrayMember({type: 'embedBlock'}),
        defineArrayMember({type: 'mapBlock'}),
        defineArrayMember({type: 'countdownTimer'}),
        defineArrayMember({type: 'metricsDashboard'}),
        defineArrayMember({type: 'cardGrid'}),
        defineArrayMember({type: 'beforeAfter'}),
      ],
      options: {
        insertMenu: {
          filter: true,
          groups: [
            {name: 'heroes', title: 'Heroes', of: ['heroBanner']},
            {
              name: 'content',
              title: 'Content',
              of: [
                'richText',
                'textWithImage',
                'faqSection',
                'articleList',
                'timeline',
                'pullquote',
                'serviceCards',
                'linkCards',
                'accordion',
                'tabsBlock',
              ],
            },
            {
              name: 'display',
              title: 'Display',
              of: [
                'teamGrid',
                'imageGallery',
                'productShowcase',
                'mapBlock',
                'cardGrid',
                'beforeAfter',
              ],
            },
            {
              name: 'media',
              title: 'Media & Stats',
              of: ['statsRow', 'featureGrid', 'videoEmbed', 'embedBlock', 'metricsDashboard'],
            },
            {
              name: 'social',
              title: 'Social Proof',
              of: [
                'sponsorCards',
                'projectCards',
                'logoCloud',
                'sponsorSteps',
                'testimonials',
                'eventList',
                'sponsorshipTiers',
              ],
            },
            {name: 'data', title: 'Data', of: ['comparisonTable', 'pricingTable']},
            {name: 'cta', title: 'Calls to Action', of: ['ctaBanner', 'contactForm', 'newsletter']},
            {
              name: 'utility',
              title: 'Utility',
              of: ['divider', 'announcementBar', 'countdownTimer'],
            },
          ],
          views: [
            {name: 'list'},
            {name: 'grid', previewImageUrl: (type: string) => `/static/block-previews/${type}.png`},
          ],
        },
      },
    }),
    defineField({
      name: 'footerBlocks',
      title: 'Footer Blocks',
      description: 'Optional content blocks rendered BELOW the listing.',
      type: 'array',
      of: [
        defineArrayMember({type: 'heroBanner'}),
        defineArrayMember({type: 'featureGrid'}),
        defineArrayMember({type: 'sponsorCards'}),
        defineArrayMember({type: 'richText'}),
        defineArrayMember({type: 'ctaBanner'}),
        defineArrayMember({type: 'faqSection'}),
        defineArrayMember({type: 'contactForm'}),
        defineArrayMember({type: 'logoCloud'}),
        defineArrayMember({type: 'statsRow'}),
        defineArrayMember({type: 'sponsorSteps'}),
        defineArrayMember({type: 'textWithImage'}),
        defineArrayMember({type: 'testimonials'}),
        defineArrayMember({type: 'eventList'}),
        defineArrayMember({type: 'projectCards'}),
        defineArrayMember({type: 'teamGrid'}),
        defineArrayMember({type: 'imageGallery'}),
        defineArrayMember({type: 'articleList'}),
        defineArrayMember({type: 'comparisonTable'}),
        defineArrayMember({type: 'timeline'}),
        defineArrayMember({type: 'pullquote'}),
        defineArrayMember({type: 'divider'}),
        defineArrayMember({type: 'announcementBar'}),
        defineArrayMember({type: 'sponsorshipTiers'}),
        defineArrayMember({type: 'videoEmbed'}),
        defineArrayMember({type: 'pricingTable'}),
        defineArrayMember({type: 'serviceCards'}),
        defineArrayMember({type: 'productShowcase'}),
        defineArrayMember({type: 'linkCards'}),
        defineArrayMember({type: 'newsletter'}),
        defineArrayMember({type: 'accordion'}),
        defineArrayMember({type: 'tabsBlock'}),
        defineArrayMember({type: 'embedBlock'}),
        defineArrayMember({type: 'mapBlock'}),
        defineArrayMember({type: 'countdownTimer'}),
        defineArrayMember({type: 'metricsDashboard'}),
        defineArrayMember({type: 'cardGrid'}),
        defineArrayMember({type: 'beforeAfter'}),
      ],
      options: {
        insertMenu: {
          filter: true,
          groups: [
            {name: 'heroes', title: 'Heroes', of: ['heroBanner']},
            {
              name: 'content',
              title: 'Content',
              of: [
                'richText',
                'textWithImage',
                'faqSection',
                'articleList',
                'timeline',
                'pullquote',
                'serviceCards',
                'linkCards',
                'accordion',
                'tabsBlock',
              ],
            },
            {
              name: 'display',
              title: 'Display',
              of: [
                'teamGrid',
                'imageGallery',
                'productShowcase',
                'mapBlock',
                'cardGrid',
                'beforeAfter',
              ],
            },
            {
              name: 'media',
              title: 'Media & Stats',
              of: ['statsRow', 'featureGrid', 'videoEmbed', 'embedBlock', 'metricsDashboard'],
            },
            {
              name: 'social',
              title: 'Social Proof',
              of: [
                'sponsorCards',
                'projectCards',
                'logoCloud',
                'sponsorSteps',
                'testimonials',
                'eventList',
                'sponsorshipTiers',
              ],
            },
            {name: 'data', title: 'Data', of: ['comparisonTable', 'pricingTable']},
            {name: 'cta', title: 'Calls to Action', of: ['ctaBanner', 'contactForm', 'newsletter']},
            {
              name: 'utility',
              title: 'Utility',
              of: ['divider', 'announcementBar', 'countdownTimer'],
            },
          ],
          views: [
            {name: 'list'},
            {name: 'grid', previewImageUrl: (type: string) => `/static/block-previews/${type}.png`},
          ],
        },
      },
    }),
  ],
})
