import {defineType, defineField, defineArrayMember} from 'sanity'
import {DocumentIcon} from '@sanity/icons'
import {siteField} from '../fields/site-field'

export const page = defineType({
  name: 'page',
  title: 'Page',
  type: 'document',
  icon: DocumentIcon,
  preview: {
    select: {title: 'title', subtitle: 'slug.current'},
  },
  groups: [
    {name: 'layout', title: 'Layout', default: true},
    {name: 'content', title: 'Content'},
    {name: 'seo', title: 'SEO'},
  ],
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'layout',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'layout',
      options: {source: 'title', maxLength: 96},
      validation: (Rule) => Rule.required(),
    }),
    {...siteField, group: 'layout'},
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
    defineField({
      name: 'blocks',
      title: 'Page Blocks',
      type: 'array',
      group: 'content',
      of: [
        defineArrayMember({type: 'heroBanner'}),
        defineArrayMember({type: 'featureGrid'}),
        defineArrayMember({type: 'sponsorCards'}),
        defineArrayMember({type: 'richText'}),
        defineArrayMember({type: 'ctaBanner'}),
        defineArrayMember({type: 'faqSection'}),
        defineArrayMember({type: 'contactForm'}),
        defineArrayMember({type: 'logoCloud'}),
        defineArrayMember({type: 'statsRow'}),
        defineArrayMember({type: 'sponsorSteps'}),
        defineArrayMember({type: 'textWithImage'}),
        defineArrayMember({type: 'testimonials'}),
        defineArrayMember({type: 'eventList'}),
        defineArrayMember({type: 'projectCards'}),
        defineArrayMember({type: 'teamGrid'}),
        defineArrayMember({type: 'imageGallery'}),
        defineArrayMember({type: 'articleList'}),
        defineArrayMember({type: 'comparisonTable'}),
        defineArrayMember({type: 'timeline'}),
        defineArrayMember({type: 'pullquote'}),
        defineArrayMember({type: 'divider'}),
        defineArrayMember({type: 'announcementBar'}),
        defineArrayMember({type: 'sponsorshipTiers'}),
        defineArrayMember({type: 'videoEmbed'}),
        // Essential blocks (Story 17.20)
        defineArrayMember({type: 'pricingTable'}),
        defineArrayMember({type: 'serviceCards'}),
        defineArrayMember({type: 'productShowcase'}),
        defineArrayMember({type: 'linkCards'}),
        defineArrayMember({type: 'newsletter'}),
        defineArrayMember({type: 'accordion'}),
        defineArrayMember({type: 'tabsBlock'}),
        defineArrayMember({type: 'embedBlock'}),
        defineArrayMember({type: 'mapBlock'}),
        defineArrayMember({type: 'countdownTimer'}),
        defineArrayMember({type: 'metricsDashboard'}),
        defineArrayMember({type: 'cardGrid'}),
        defineArrayMember({type: 'beforeAfter'}),
      ],
      options: {
        insertMenu: {
          filter: true,
          groups: [
            {name: 'heroes', title: 'Heroes', of: ['heroBanner']},
            {
              name: 'content',
              title: 'Content',
              of: ['richText', 'textWithImage', 'faqSection', 'articleList', 'timeline', 'pullquote', 'serviceCards', 'linkCards', 'accordion', 'tabsBlock'],
            },
            {
              name: 'display',
              title: 'Display',
              of: ['teamGrid', 'imageGallery', 'productShowcase', 'mapBlock', 'cardGrid', 'beforeAfter'],
            },
            {
              name: 'media',
              title: 'Media & Stats',
              of: ['statsRow', 'featureGrid', 'videoEmbed', 'embedBlock', 'metricsDashboard'],
            },
            {name: 'social', title: 'Social Proof', of: ['sponsorCards', 'projectCards', 'logoCloud', 'sponsorSteps', 'testimonials', 'eventList', 'sponsorshipTiers']},
            {name: 'data', title: 'Data', of: ['comparisonTable', 'pricingTable']},
            {name: 'cta', title: 'Calls to Action', of: ['ctaBanner', 'contactForm', 'newsletter']},
            {name: 'utility', title: 'Utility', of: ['divider', 'announcementBar', 'countdownTimer']},
          ],
          views: [
            {name: 'list'},
            {name: 'grid', previewImageUrl: (type: string) => `/static/block-previews/${type}.png`},
          ],
        },
      },
    }),
  ],
})
