import {defineType, defineField, defineArrayMember} from 'sanity'
import {ProjectsIcon, SearchIcon} from '@sanity/icons'
import {siteField} from '../fields/site-field'

export const project = defineType({
  name: 'project',
  title: 'Project',
  type: 'document',
  icon: ProjectsIcon,
  groups: [
    {name: 'main', title: 'Main', default: true},
    {name: 'content', title: 'Content'},
    {name: 'team', title: 'Team'},
    {name: 'tags', title: 'Tags'},
    {name: 'seo', title: 'SEO', icon: SearchIcon},
  ],
  preview: {
    select: {title: 'title', subtitle: 'semester', media: 'sponsor.logo'},
  },
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      group: 'main',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      group: 'main',
      options: {source: 'title'},
      validation: (Rule) => Rule.required(),
    }),
    {...siteField, group: 'main'},
    defineField({
      name: 'sponsor',
      title: 'Sponsor',
      type: 'reference',
      group: 'main',
      to: [{type: 'sponsor'}],
    }),
    defineField({
      name: 'status',
      title: 'Status',
      type: 'string',
      group: 'main',
      options: {
        list: [
          {title: 'Active', value: 'active'},
          {title: 'Completed', value: 'completed'},
          {title: 'Archived', value: 'archived'},
        ],
      },
      initialValue: 'active',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'semester',
      title: 'Semester',
      type: 'string',
      group: 'main',
    }),
    defineField({
      name: 'content',
      title: 'Content',
      type: 'portableText',
      group: 'content',
    }),
    defineField({
      name: 'outcome',
      title: 'Outcome & Impact',
      type: 'text',
      group: 'content',
    }),
    defineField({
      name: 'team',
      title: 'Team Members',
      type: 'array',
      group: 'team',
      of: [
        defineArrayMember({
          type: 'object',
          fields: [
            defineField({
              name: 'name',
              title: 'Name',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'role',
              title: 'Role',
              type: 'string',
            }),
          ],
          preview: {select: {title: 'name', subtitle: 'role'}},
        }),
      ],
    }),
    defineField({
      name: 'mentor',
      title: 'Mentor',
      type: 'string',
      group: 'team',
    }),
    defineField({
      name: 'technologyTags',
      title: 'Technologies',
      type: 'array',
      group: 'tags',
      of: [
        defineArrayMember({
          type: 'string',
          options: {
            list: [
              {title: '5G Technology', value: '5G Technology'},
              {title: '802.1X Authentication', value: '802.1X Authentication'},
              {title: 'AI/ML', value: 'AI/ML'},
              {title: 'Angular', value: 'Angular'},
              {title: 'Astro', value: 'Astro'},
              {title: 'AWS', value: 'AWS'},
              {title: 'Azure ML', value: 'Azure ML'},
              {title: 'Big Data', value: 'Big Data'},
              {title: 'Blockchain', value: 'Blockchain'},
              {title: 'CSS', value: 'CSS'},
              {title: 'Cisco Packet Tracer', value: 'Cisco Packet Tracer'},
              {title: 'Cloud Computing', value: 'Cloud Computing'},
              {title: 'Computer Vision', value: 'Computer Vision'},
              {title: 'Custom Theme', value: 'Custom Theme'},
              {title: 'DNS Security', value: 'DNS Security'},
              {title: 'Data Analytics', value: 'Data Analytics'},
              {title: 'Data Science', value: 'Data Science'},
              {title: 'Data Visualization', value: 'Data Visualization'},
              {title: 'Distributed Systems', value: 'Distributed Systems'},
              {title: 'Docker', value: 'Docker'},
              {title: 'Edge Computing', value: 'Edge Computing'},
              {title: 'EdTech', value: 'EdTech'},
              {title: 'Elementor', value: 'Elementor'},
              {title: 'Ethereum', value: 'Ethereum'},
              {title: 'Firebase', value: 'Firebase'},
              {title: 'FormSite', value: 'FormSite'},
              {title: 'Gamification', value: 'Gamification'},
              {title: 'Git', value: 'Git'},
              {title: 'GraphQL', value: 'GraphQL'},
              {title: 'HTML', value: 'HTML'},
              {title: 'Healthcare IoT', value: 'Healthcare IoT'},
              {title: 'IoT', value: 'IoT'},
              {title: 'Java', value: 'Java'},
              {title: 'JavaScript', value: 'JavaScript'},
              {title: 'Kubernetes', value: 'Kubernetes'},
              {title: 'Machine Learning', value: 'Machine Learning'},
              {title: 'MongoDB', value: 'MongoDB'},
              {title: 'MySQL', value: 'MySQL'},
              {title: 'NLP', value: 'NLP'},
              {title: 'Network Security', value: 'Network Security'},
              {title: 'Next.js', value: 'Next.js'},
              {title: 'Node.js', value: 'Node.js'},
              {title: 'Optimization', value: 'Optimization'},
              {title: 'PHP', value: 'PHP'},
              {title: 'PostgreSQL', value: 'PostgreSQL'},
              {title: 'Proof-of-Stake', value: 'Proof-of-Stake'},
              {title: 'Publishing', value: 'Publishing'},
              {title: 'Python', value: 'Python'},
              {title: 'RADIUS Server', value: 'RADIUS Server'},
              {title: 'REST API', value: 'REST API'},
              {title: 'React', value: 'React'},
              {title: 'Sentiment Analysis', value: 'Sentiment Analysis'},
              {title: 'Smart Contracts', value: 'Smart Contracts'},
              {title: 'Smart Slider 3', value: 'Smart Slider 3'},
              {title: 'Social Impact', value: 'Social Impact'},
              {title: 'Sustainability', value: 'Sustainability'},
              {title: 'Tailwind CSS', value: 'Tailwind CSS'},
              {title: 'TypeScript', value: 'TypeScript'},
              {title: 'VLAN Configuration', value: 'VLAN Configuration'},
              {title: 'Video Processing', value: 'Video Processing'},
              {title: 'Vue.js', value: 'Vue.js'},
              {title: 'Web Development', value: 'Web Development'},
              {title: 'WebRTC', value: 'WebRTC'},
              {title: 'WordPress', value: 'WordPress'},
              {title: 'Workforce Analytics', value: 'Workforce Analytics'},
              {title: 'Zero Trust Architecture', value: 'Zero Trust Architecture'},
            ],
          },
        }),
      ],
      options: {layout: 'tags'},
      validation: (Rule) => Rule.unique(),
    }),
    defineField({
      name: 'seo',
      title: 'SEO',
      type: 'seo',
      group: 'seo',
    }),
  ],
})
